language: node_js
node_js:
  - "11"

services:
  - docker

cache: yarn

before_script:
  - yarn

script:
  - yarn build

deploy:
  provider: script
  # script: echo "$DOCKER_PASSWORD" | docker login -u botanicus --password-stdin && docker push botanicus/blog
  script: echo "$HEROKU_PASSWORD" | docker login -u botanicus --password-stdin registry.heroku.com && heroku container:login && heroku container:push web && heroku container:release web
  branch: master
