language: node_js

node_js:
  - "11"

notifications:
  email: false

services:
  - docker

cache: yarn

script:
  - rake travis:build

deploy:
  provider: script
  script: rake travis:deploy
  branch: master
