language: node_js
node_js:
  - "11"

services:
  - docker

cache: yarn

script:
  - yarn build

deploy:
  provider: script
  # script: echo "$DOCKER_PASSWORD" | docker login -u botanicus --password-stdin && docker push botanicus/blog
  script: echo "$HEROKU_PASSWORD" | docker login -u botanicus --password-stdin registry.heroku.com && heroku container:push web -a botanicus-me && heroku container:release web -a botanicus-me
  branch: master
