language: node_js
node_js:
  - "8"

services:
  - docker

cache: yarn

before_script:
  - yarn

script:
  - yarn build
  - docker build . -t botanicus/blog

deploy:
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u botanicus --password-stdin
    - docker push botanicus/blog
