language: node_js

node_js:
  - "11"

notifications:
  email: false

services:
  - docker

cache: yarn

script:
  - yarn build
  - docker build . -t registry.heroku.com/botanicus-me/web

deploy:
  provider: script
  script: rake travis:deploy
  branch: master
