language: node_js

node_js:
  - "11"

services:
  - docker

addons:
  apt:
    packages:
      - libgconf-2-4 # Cypress

cache:
  yarn: true
  directories:
    - ~/.cache # Cache the Cypress binary.

script:
  - yarn test src/*/*.test.js
  - yarn start & wait-on http://localhost:3000 && yarn cypress
  - rake travis:build

deploy:
  provider: script
  script: rake travis:deploy
  branch: master

notifications:
  email: no

  # https://docs.travis-ci.com/user/notifications/#configuring-pushover-notifications
  pushover:
    on_failure: always
    on_success: change
    api_key:
      secure: dBTyI4bYHv9OumMVAmJvaimUNCJ6Kqkog2Z/UlTzH+gC8dQcc/GnRzE4NJXgYnZy8+Gi+mGFOJUEa2rV+3r6eFZWCGh2JSi1jLs2X6QOqZInOpV5c1pIRCOhbIdxoU4BcFeqIk53DvovPZTi1fa1moXq853RjZ40erZjSQecmSptsDAxCZ9l9OhhLWzMwnH+oURKMZSM7ru6+00tth7vwyTOWKIjUsBHrovpndIuAG16TC2x3/a15ujm1pqh+zev+fL4uHiF/2sGsXhTTDMI/J/CIBxsWDigIu7+T5iPayBQDY0jzMq10A4vM5T50f8IuqT4qnyUo0Wg4m72BLi5moy7WCODtaZFylBlJKy+nOfRdqxdmHo0cfQmjvOQ1UmF66FGgHQyvs4cG6VkugARoFw5uu58eByiKHaZIbuReI/gkqUF/2k+Ge6SpeocWr/nBDXSgLiRaaNItvKfliZ3wAUCfWmkf95pSKWJRekMe0+19K7kITBYXdzZ6SoOzWhel+AEho4htvlXXFV4JMM1a6EkJkOuM+XhOfqnPP8iPWprHtcLBnMT7a/x6gY90reCa0wV8a404EAchBUulvX4+cERByTJc0xPHa/5P298X+JoZtH73IjqHCvoPURgwdxUqmt/vD0V31rCWOhJGEY97vJVzexDmb5n8wU3FlVWOtE=
    users:
    - secure: ijWPOkk7h7SJ8BKzp1BXZWaPmvlFm01lo0aRc/1P9S3ZbkV3crXx9yRwAf2ME9FZpJI9WignEqmVPeIlBB/Mba7npWovaS7M2EeK/RoS0W3Z2yoYhcEOB10/oXg7Nbgz5XQaganpaYdQIijPY9E8Kw96foDkfLYj7kZw0AW1IwCzY6KFz3BRqI4N4KCbiJ75kom9ojivYzKeZPaShAc0rAEESLamQYcTv01SUS1Ij5g4Yf8RV4qsmw7YcxZXSctXtXuCDYFhi5TKKmSHHzoF4SZ6wOMNGaJhD0Ga/u2tS+zULPBMPL9LQm7qjDvd/RZG1N01xko26v2rybe6yOGxT11CVFUoX0b2q8zXDa8W4EN+lhUxOGeE935ze66xslPEy6NIXbsI4u+r6PgHrPTC9ClINHr/hMr4jqXXF2BgQqdbJ+esSBcoI3IzO7NdiDqALz43suRYn0XpxjCjF8GH7kWx+RMxtociPLO/IpaGeP6g1llEv07Bqzm/IMeCP0afU+DaJnmCsrRczktbqv+DbLWC0yqP4OAZK7rpDZJMMaaI2Tjj32L+raE5jLe3Iy4/gckfpGyIkE2YeL4FTAbXtsJkJUTaX+byfXVd7hZXK/b8kloMN1zUv3+KZCeM4eghUwvwc7ZI/9XBDltXo0rpe7sKEoYyx/riQSZ4uJ5F7UU=
