NAME = 'jakubstastny/blog-backend'

desc "Run the app"
task :run do
  sh "bundle exec rackup --port 5000"
end

desc "Build the Docker image"
task :build do
  sh "docker build . -t #{NAME}"
end

desc "Push the image to DockerHub"
task :push do
  sh "docker push #{NAME}"
end
